### ISSUE TITLE
Small Cosmetic Nits on help

### ISSUE THREAD

**Issue by wd5gnr** [audiohacked/OpenCorsairLink#1]
CLI Help: The led mode is shown in hex (0x80) but the program doesn't strip off the 0x. A few examples at the end might help. Also, no indication of the cycle speed (is 1 fast or F fast? Is zero legal?) 

Suggest adding.

Examples:
Slow fade between Red, Green, and Blue:
OpenCorsairLinkCli -l 1 --led-mode 80 --rgb1 FF0000 --rgb2 00FF00 --rgb3 0000FF --rgb4 FFFFFF

Fast fade between Red, Green, and Blue:
OpenCorsairLinkCli -l 1 --led-mode 8f --rgb1 FF0000 --rgb2 00FF00 --rgb3 0000FF --rgb4 FFFFFF

Note: If USB device is owned by root, the commands may need to be run as root.

**Comment by zeroepoch** [comment]
Fan number 5 for the pump is not documented anywhere except a comment in a header file and from the bounds check on the input.  While I don't know if it makes a difference you can set the pump speed.  On my H80i it doesn't seem to change anything other than the print out.
