### ISSUE TITLE
wrong color?

### ISSUE THREAD

**Issue by ghost** [audiohacked/OpenCorsairLink#10]
Hello,

I've got an H110i on my desktop and I wanted to enable the feature that changes the LED color based on the cpu temperature.

I run the following command, which I expected to set the 3 colors to white, yellow and red:

```
./OpenCorsairLinkCli --led 1 --led-mode C0 --rgb1 ffffff --rgb2 ffff00 --rgb3 ff0000
```

But the LED changed to green!

Here is the output from the -print parameter:

```
./OpenCorsairLinkCli -p
H110i: Firmware v1108

Number of Controllable LEDs: 1
LED Mode: C0
LED Color:
    Red: 0
    Green: 205
    Blue: 49
...
```

Based on the documentation, I'm supposed to set the 3 rgb colors by using HTML color codes.

Any help would be appreciated.

Thank you.

**Comment by jsmad** [comment]
Well, I did a few tests with all sorts of colors and I've found out that no matter what color I try, none of them work. It always works with turquoise (cool) to sickly green (hot).
