### ISSUE TITLE
Implement LED control for Commander Pro

### ISSUE THREAD

**Issue by audiohacked** [audiohacked/OpenCorsairLink#101]
Due to the complexity of the LED commanding in the Commander Pro, I've been thinking of implementing a "LED Control" structure to hold all the possible LED settings and pass that to the LED functions; instead of passing individual parameters for the LEDs. What does everyone think? @PostalBlab @pvh1987

**Comment by PostalBlab** [comment]
Very good idea. Implementing this without a structure would be a big mess an pita. Sadly i own only a H110i GT and can't help with this.
@audiohacked did you get my mail?

**Comment by audiohacked** [comment]
@PostalBlab I did

**Comment by pvh1987** [comment]
I agree that this would be the best solution. The LED related commands in the Commander Pro is a bit complicated compared to the rest of the functionality. The original Corsair LINK software seems to transmit several LED commands in groups, each time a setting is changed. So it makes sense to do something similar, also to avoid messy code.

**Comment by audiohacked** [comment]
I think I need to revamp the command line options before tackling the led control "packet". Commander Pro has a bunch of options, but the hard part is dealing with 2 LED channels. Having Sub-Options for the led options will allow defining all options for each LED channel something like: "--led channel=2,mode=static,colors=00FF00|FFFF00|0000FF"

**Comment by audiohacked** [comment]
Testing branch has preliminary (and untested) code for the Commander Pro LED subsystem

**Comment by audiohacked** [comment]
@vlinkz Most of the reverse engineering is completed, but there could be work done on the logic and such.

**Comment by TLable** [comment]
I was able to change LED by choosing channel=1,2 then 3 and testing color codes starting with numbers and eding with numbers then ending with the colour I wanted to change it to. It turns on and off and changes colors from red,blue,green. I had to turn the colors off first then on and change to the colors I wanted. 

sudo ./OpenCorsairLink.elf --dev=0 --led channel=2,mode=0,colors=##:##:##

**Comment by eitch** [comment]
Am i missing something, when i try to set the LED of my commander pro i get "Unsupported Generic LED Function" error:

sudo ./OpenCorsairLink.elf --dev=1 --led channel=2,mode=0,colors=00FF00

    Dev=0, CorsairLink Device Found: Lighting Node PRO!
    Dev=1, CorsairLink Device Found: Commander PRO!
    Dev=2, CorsairLink Device Found: Obsidian 1000D Commander Pro!

    Vendor: Corsair
    Product: Commander PRO
    Firmware: V0.8.210
    Temperature 0: 30.73 C
    Temperature 1: 29.75 C
    Temperature 2:  0.00 C
    Temperature 3:  0.00 C
    Output 12v: 12.21 V
    Output 5v:  4.99 V
    Output 3.3v:  3.40 V
    Fan 0:	Mode: Auto/Disconnected
    	PWM: 0%
    	RPM: 769
    Fan 1:	Mode: Auto/Disconnected
    	PWM: 0%
    	RPM: 699
    Fan 2:	Mode: Auto/Disconnected
    	PWM: 0%
    	RPM: 683
    Fan 3:	Mode: Auto/Disconnected
    	PWM: 0%
    	RPM: 722
    Fan 4:	Mode: Auto/Disconnected
    	PWM: 0%
    	RPM: 732
    Fan 5:	Mode: Auto/Disconnected
    	PWM: 0%
    	RPM: 690
    Unsupported Generic LED Function

**Comment by audiohacked** [comment]
Closing this until we encounter issues....
