### ISSUE TITLE
Add support for old CoolIT protocol

### ISSUE THREAD

**Issue by PostalBlab** [audiohacked/OpenCorsairLink#103]
As documented in the wiki, there is not only one HID protocol for all CoolIT devices, but three. 
I would suggest to implement, like in CorsairLink, the "old world" and "modern" protocols and rename all "hid" stuff to coolit_old or something like that. If i got your ok @audiohacked i would start working on this.

**Comment by audiohacked** [comment]
Sounds good to me!
