### ISSUE TITLE
Please explain how to install this? Getting 'make' errors

### ISSUE THREAD

**Issue by B33Z5z** [audiohacked/OpenCorsairLink#107]
The last time i installed this was from the legacy version and got some help from https://forum.level1techs.com/t/corsair-h100i-linux-howto/75829
However that procedure doesnt help anymore with the new version.

On ubuntu 18.04 have installed the depenencies: pkg-config libusb-1.0-0-dev

What are the next steps to actually compile, build & install this ??
thanks

**Comment by audiohacked** [comment]
It's just `make`. And at the moment there's no install.

**Comment by B33Z5z** [comment]
Well, i just re-cloned now in the dir, and re-typed make and it worked. Thats strange. I see that you made a commit 20min ago. maybe something was wrong.
