### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ssmoss** [audiohacked/OpenCorsairLink#110]
I have been trying to find some good documentation on configure my H80i V2. Would it be possible to explain what the different channels are for settings the LEDs and some more information on choosing values / fan modes for general purpose operation? I am happy to collect the information and formulate a into HOWTO of something of that nature.

**Comment by audiohacked** [comment]
The H80i V2 has no LED channels and only supports Static color LED mode. As for Fans, the H80i V2 has two Profiles: Performance and Quiet. You could define your own Fan Curve, but you should leave settings as is.
