### ISSUE TITLE
Custom curves not supported?

### ISSUE THREAD

**Issue by DanySK** [audiohacked/OpenCorsairLink#111]
Hi,
I am experimenting in the master branch, and I believe the manual control of fan speed over temperatures is not working. In fact, seems to me that `SUBOPTION_FAN_TEMPS` and `SUBOPTION_FAN_SPEEDS` are entirely ignored in `options_fan.c`.

Executing:
`sudo ./OpenCorsairLink.elf --device 0 --pump mode=3 --fan mode=6,temps="0:20:25:30:35:40",speeds="0:10:30:60:80:100"`

causes:
```
Unknown suboption `0:20:25:30:35:40'
Unknown suboption `0:10:30:60:80:100'
```

Are custom curves a work in progress?

**Comment by chenyangh** [comment]
Yes, I found the same. And it was supported in an older version.

**Comment by audiohacked** [comment]
@DanySK Yes, custom curves are a work in progress. Support was dropped due to the rewrite of the command line option parser.

**Comment by audiohacked** [comment]
By the way, you should be on Testing Branch.

**Comment by DanySK** [comment]
Switched branch. I still see inconsistencies:
```
Fan:
        --fan channel=N,mode=N,pwm=PWM,rpm=RPM,temps=TEMP:TEMP:TEMP,speeds=SPEED:SPEED:SPEED
```
but right below:
```
temps <CSV of Temperatures>     :Define Comma Separated Values of Temperatures for Fan.
                speeds <CSV of Speed Percentage>        :Define Comma Separated Values of RPM Percentage for Fan.
```
Which syntax would you like to support? I believe that with the current `getsubopt` parsing it'd be way easier to support a colon separator.

**Comment by DanySK** [comment]
I'd like some clarifications about `struct option_parse_return`. It is unclear to me what `struct fan_table fan1` and `struct fan_table pump` represent, as they seem to me redundant w.r.t. `struct fan_control fan_ctrl` and `struct pump_control pump_ctr`. The latter two are currently unused: are them a leftover from a refactoring, or are them supposed to replace `fan1` and `pump`?

**Comment by audiohacked** [comment]
`struct fan_control` and `struct pump_control` are intended to replace all the other variables in `struct option_parse_return`

**Comment by DanySK** [comment]
Closed means that the support is now there, that you are working on it but not accepting contributions, that they won't be supported, or what?

**Comment by audiohacked** [comment]
Working on it, but if you provide a pull request that includes support I'll take it.

**Comment by DanySK** [comment]
Sure, I'm willing to help, I need your guidance though as I'm not expert of the Corsair AIOs internals, and I can only test on my own H100i.
I could start with parsing the subcommand for temps and speeds and populating `struct option_parse_return`. If you agree, I'd use the new `fan_ctrl` and `pump_ctrl`.

**Comment by notlesh** [comment]
Was there a commit where this was actually working?

**Comment by audiohacked** [comment]
The main problem some devices support custom fan curves and other devices do **not** support custom fan curves. The support depends on the device in question.

**Comment by notlesh** [comment]
Oh, I see. I have a `h110i`, which I thought supported them, but I can't seem to do that under Windows at the moment.

Assuming I had a device that supported custom curves, does the current or any past version of `OpenCorsairLink` support this?

**Comment by audiohacked** [comment]
@notlesh If you have a device that supports it, then any version of OpenCorsairLink that supports that device will have support for custom curves.
