### ISSUE TITLE
Lighting Node Pro -- Doesn't Change Color

### ISSUE THREAD

**Issue by typedrat** [audiohacked/OpenCorsairLink#116]
I'm using a lighting node pro with two LL140 fans, and while it's detected the color does not change when the appropriate command is sent.

**Comment by audiohacked** [comment]
The support for the Lighting Node Pro hasn't been completed yet!

**Comment by Jarrio** [comment]
I am currently experiencing this issue as well, I run the following command 
```sudo ./OpenCorsairLink.elf --led channel=2,mode=0,colors=FFFFFF```
I get the following response:
```Dev=0, CorsairLink Device Found: Lighting Node PRO```
But my fans do not change colour
