### ISSUE TITLE
H100i GTX gets all zero response

### ISSUE THREAD

**Issue by merrickluo** [audiohacked/OpenCorsairLink#117]
I tried testing branch, and master~1 commit ( master branch won't compile with a `getsubopt` not defined error.

All outputs are zero:  [debug output](https://gist.github.com/merrickluo/77c8b25ddb473c4d55274419431eaf15)

When I revert back to the first commit added H100i GTX support 83e167b71f734e24df6193b651c0eddad52be437 it works fine. [debug output](https://gist.github.com/merrickluo/fd5f28b05c5032f35a8599d2adefe3f2)

After trying several commits after that, I think this 7c00ffc6b1473d366942131e2098dc94d6d58fb8 commit makes it become zero, but I have no idea why.

**Comment by audiohacked** [comment]
The H100i GTX is based on the Asetek Protocol, and I have tested against my Asetek device and you should be getting values out. If not, something might be interfering with OpenCorsairLink!
