### ISSUE TITLE
H80i GT V2!  I get no results

### ISSUE THREAD

**Issue by cybernard** [audiohacked/OpenCorsairLink#119]
Dev=0, CorsairLink Device Found: H80i GT V2!

This is all I get.

dmesg says:
 usb 3-2: New USB device found, idVendor=1b1c, idProduct=0c08, bcdDevice= 1.00
 usb 3-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
 usb 3-2: Product: H80i v2
 usb 3-2: Manufacturer: Corsair Components, Inc.
 usb 3-2: SerialNumber: 7289_2.0
 usb 3-2: new full-speed USB device number 3 using xhci_hcd

**Comment by audiohacked** [comment]
Did you run with "--device 0"

**Comment by audiohacked** [comment]
Closing due to a miss understanding of how to run OpenCorsairLink. Executing the software without command line arguments will only print out what devices that are detected, nothing more.
