### ISSUE TITLE
Fans are every time at full power after running an command (H100i v2)

### ISSUE THREAD

**Issue by Flova** [audiohacked/OpenCorsairLink#132]
Since the Issue with the fan speeds changing randomly after running an command is fixed, the following behavior occurs. The fans are going up to 100% after running a single command which affects the fan speed control.

As an example the following command results in the described behavior.
```bash
sudo OpenCorsairLink --device 0 --fan channel=0 mode=1 rpm=800
```

**Comment by audiohacked** [comment]
You have the wrong command format.
