### ISSUE TITLE
Submodule access

### ISSUE THREAD

**Issue by ccopol** [audiohacked/OpenCorsairLink#14]
Can you use the https protocole instead of the ssh one to access your submodule. I was not able to update the module by using ssh.

**Comment by audiohacked** [comment]
I'm using SSH so that I can commit to the submodule in tree. But I'll change it just for you!

**Comment by ccopol** [comment]
Thank it's not necessary. I've just updated the .gitmodule to put https
instead of ssh. But I  think it would be a better solution for other people
if you use https.
