### ISSUE TITLE
H80i Custom curves not working

### ISSUE THREAD

**Issue by minisori** [audiohacked/OpenCorsairLink#140]
First of all, nice work!

I'm not sure if it's implemented for this device but i have the next problem:
Custom curves are not working with H80i, looks like it does nothing. In fact only default, quiet, balanced and performance profiles are working.

**To Reproduce**
OpenCorsairLink --device 0 --fan channel=0,mode=6,temps=34:36:38,speeds=50:60:80

**Expected behavior**
I expect OpenCorsairLink to report custom curve on fan 0, but reports whatever profile was set.

**Dump info**
OpenCorsairLink --device 0 --fan channel=0,mode=6,temps=34:36:38,speeds=50:60:80 --dump
Checking USB device 0 (8087:8000)...
Checking USB device 1 (1d6b:0002)...
Checking USB device 2 (8087:8008)...
Checking USB device 3 (1d6b:0002)...
Checking USB device 4 (05e3:0612)...
Checking USB device 5 (174c:3074)...
Checking USB device 6 (1d6b:0003)...
Checking USB device 7 (05e3:0610)...
Checking USB device 8 (1b1c:0c04)...
Corsair product detected. Checking if device is H80... No (device_id 0x3B)
Corsair product detected. Checking if device is Cooling Node... No (device_id 0x3B)
Corsair product detected. Checking if device is Lighting Node... No (device_id 0x3B)
Corsair product detected. Checking if device is H100... No (device_id 0x3B)
Corsair product detected. Checking if device is H80i... Dev=0, CorsairLink Device Found: H80i!
Checking USB device 9 (0b05:17cf)...
Checking USB device 10 (174c:2074)...
Checking USB device 11 (2516:0009)...
Checking USB device 12 (12cf:0186)...
Checking USB device 13 (1d6b:0002)...

DEBUG: scan done, start routines
DEBUG: device_number = 0
DEBUG: shortcuts set
DEBUG: init done
Vendor: Corsair
Product: H80i
Firmware: 1.1.3
Temperature 0: 30.93 C
Fan 0:	Balanced Mode (4PIN)
	Current/Max Speed 1664/2460 RPM
Fan 1:	Balanced Mode (4PIN)
	Current/Max Speed 1623/2403 RPM
Fan 2:	Not connected or failed
	Current/Max Speed 0/0 RPM
Fan 3:	Not connected or failed
	Current/Max Speed 0/0 RPM
Pump:	Mode 0x8B
	Current/Max Speed 1664/2460 RPM
DEBUG: deinit done

**System info**
OS: Debian stretch Kernel 4.17.17-1~bpo9+1

**Comment by audiohacked** [comment]
The current code queries the current settings then modifies the settings when you make a change. You need run OpenCorsairLink without any settings to print out the "new" settings.
