### ISSUE TITLE
Temperature Report Bug for Commander Pro and Proposed Fixes

### ISSUE THREAD

**Issue by Holmeswww** [audiohacked/OpenCorsairLink#143]
**Describe the bug**
The return from the temperature sensor uses Big Endian so we cannot cast to float directly

**To Reproduce**
None

**Expected behavior**
Temperature incorrect

**Proposed Solution**
Use this code in temperature.c
    tmp[0]=response[2];
    tmp[1]=response[1];
    memcpy( &data, tmp, 2 );
    *( temperature ) = (double)data / 100;

**Comment by audiohacked** [comment]
I'm closing this Issue, I think I implemented this fix in a previous commit.
