### ISSUE TITLE
Centos 7 libusb 1.0 [help wanted]

### ISSUE THREAD

**Issue by gpapaioa** [audiohacked/OpenCorsairLink#147]
Hello. Trying to make OpenCorsairLink from git on Centos 7 with no luck. Latest libusb is libusb-0.1.4-3.el7.x86_64.rpm. Should I manually upgrade libusb from https://github.com/libusb/libusb? Thank you.

**Comment by JacksonCampolattaro** [comment]
I ended up just needing to install libusb-devel (Fedora 29).

**Comment by audiohacked** [comment]
For CentOS 7 and Fedora, the libusb-1.0 is now called libusbx.
