### ISSUE TITLE
HX1200i make install and led colour don't work

### ISSUE THREAD

**Issue by FrancescoBorzi** [audiohacked/OpenCorsairLink#151]
**Describe the bug**

After `make`, I did `sudo make install` and I got:

> make: *** No rule to make target 'install'. Stop.

I tried to use this command to change colour:

```
sudo ./OpenCorsairLink.elf --device 0 --led channel=0,mode=0,color=0000CD
```

but the colour remains the same

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: PC
 - OS: Ubuntu 18.04
 - Browser: Chrome (but why does it matter?)
 - Version: `OpenCorsairLink Version: v0.9.0.0Dev=0, CorsairLink Device Found: HX1200i!`

**Comment by FrancescoBorzi** [comment]
@audiohacked you could have mentioned why the issue report is not valid and how I can make it right

**Comment by audiohacked** [comment]
@FrancescoBorzi The HX1200i doesn't have LEDs.

**Comment by audiohacked** [comment]
There is no install....

**Comment by FrancescoBorzi** [comment]
@audiohacked then we should update the `README.md`, currently saying:

![image](https://user-images.githubusercontent.com/75517/52169879-7fad5680-273f-11e9-8301-7c1873f84d84.png)

**Comment by audiohacked** [comment]
The README.md is correct, just no install support in Make.

**Comment by bmccord2** [comment]
@audiohacked This answer confuses me.  If there is no target defined in the make file named "install" how is the Makefile correct?
