### ISSUE TITLE
Contribute a Linux driver

### ISSUE THREAD

**Issue by dflemstr** [audiohacked/OpenCorsairLink#166]
It would be nice if this code base could be contributed to the Linux kernel, so that everybody would get these features without having to install anything.  For example, it would be possible to use existing system monitoring tools such as lm_sensors and other widgets.

Keeping this project as a separate executable means that you need to either always run it at boot or otherwise schedule it to be run in user space, which is a bit of a hassle.

You can find similar drivers in this tree, as an example: https://github.com/torvalds/linux/tree/master/drivers/thermal

**Comment by audiohacked** [comment]
As I would love to contribute a full Linux Driver from OpenCorsairLink. There are several technical reasons why I don't think its possible. One is the current code base uses libusb, which is a userland driver/library. Which means I would need to learn how to write a USB interface driver. Two is that there are a few different USB protocols used by CorsairLink devices. And would require writing several USB drivers; at least one for each protocol. Three is the rapid changes to the protocols and firmware for every release of CorsairLink, iCUE, etc by Corsair. Which means a huge maintenance burden on either myself or the maintainer of the USB drivers in the Linux Kernel.

I may be wrong on these points, but as I am the only one maintaining OpenCorsairLink, and as it is, is already a lot of work maintaining what is already supported.
