### ISSUE TITLE
Temperature error on H150i

### ISSUE THREAD

**Issue by msmaldi** [audiohacked/OpenCorsairLink#179]
**Describe the bug**
It is a simple bug in display temperature, after run 
`sudo ./OpenCorsairLink.elf --device 0`
`
...
Temperature 0: 36.05 C
...
`
but temperature is 36.5

**To Reproduce**
1. Start a application thats use all clocks 100%
2. Temperature go:
30.01
30.02
30.03
...
30.09
31.00

never exist 30.10, 30.11

Correct is
30.1
30.2
...
30.9

**Comment by audiohacked** [comment]
How do you know that the temperature is suppose to be 36.5 when OCL prints 36.05?

**Comment by msmaldi** [comment]
Why i temperature never between 30.10 and 30.99, 31.10 and 31.99
After 30,09 go direct to 31.00

**Comment by msmaldi** [comment]
I think error is in file protocol/asetekpro/temperature
`    *( temperature ) = (double)response[3] + ( (double)response[4] / 100 );`
Correct
`    *( temperature ) = (double)response[3] + ( (double)response[4] / 10 );`

I have no time now to fix.

**Comment by jlask** [comment]
I had to revert this commit otherwise I was getting all zeroes for temp/fan output values.    

I also see, "Unable to detach kernel driver from Corsair".

I have the H100i Pro.
