### ISSUE TITLE
No output for RM1000i

### ISSUE THREAD

**Issue by viggy96** [audiohacked/OpenCorsairLink#187]
**Describe the bug**
No output with RM1000i

**Expected behavior**
Power usage data is outputted

**Desktop (please complete the following information):**
 - OS: Manjaro 18.0.4

**Comment by teamalpha5441** [comment]
Can confirm this, RM1000i is detected, but no output.

**Comment by viggy96** [comment]
For me, the RM1000i is not even detected.

**Comment by teamalpha5441** [comment]
It maybe was an error on my side, device is detected now and information looks fine.
`sudo ./OpenCorsairLink.elf --device 0`
Works with master and testing branch.
