### ISSUE TITLE
Mismatch between H110i GT V2 and H115i

### ISSUE THREAD

**Issue by source83** [audiohacked/OpenCorsairLink#197]
**Describe the bug**
The H110i GT V2 seems to have the same device ID as the H115i has.
lsusb: ```Bus 001 Device 006: ID 1b1c:0c0a Corsair```

[H115i.txt](https://github.com/audiohacked/OpenCorsairLink/files/3521861/H115i.txt)

**Comment by audiohacked** [comment]
@source83 Your H115i probably **is** an H110i GT V2. Corsair/Coolit devices have been frequently renamed.

**Comment by source83** [comment]
Aaah, that'd explain it
