### ISSUE TITLE
make on Linux mint 18.1 (ubuntu 16.04)

### ISSUE THREAD

**Issue by jontis** [audiohacked/OpenCorsairLink#20]
fails with:
$ make
cc -std=c99 -pedantic-errors -I/usr/include/libusb-1.0 -lm -lusb-1.0 main.o device.o driver.o options.o print.o scan.o protocol/asetek4/core.o protocol/asetek4/fan.o protocol/asetek4/led.o protocol/asetek4/pump.o protocol/asetek4/temperature.o protocol/rmi/core.o protocol/rmi/power.o protocol/rmi/temperature.o protocol/rmi/time.o protocol/hid/core.o protocol/hid/led.o protocol/hid/temperature.o lowlevel/asetek4.o lowlevel/hid.o lowlevel/rmi.o -o OpenCorsairLink.elf 
main.o: In function `main':
/home/jonathan/code/openCorsairLink/OpenCorsairLink/main.c:172: undefined reference to `libusb_init'
/home/jonathan/code/openCorsairLink/OpenCorsairLink/main.c:177: undefined reference to `libusb_set_debug'

and a whole lot more relating to libusb functions. I have installed libusb-1.0-0-dev and I'm pretty sure it is found because I had other errors before.

**Comment by audiohacked** [comment]
Apparently GCC has problems with the order of LDFLAGS and the objects being linked, latest commit fixes this.
