### ISSUE TITLE
Unsupported Generic Pump Function for H80i GT V2

### ISSUE THREAD

**Issue by JoshDi** [audiohacked/OpenCorsairLink#217]
**Describe the bug**
When trying to change the pump speed on the Corsair H80i GT V2, I get the error "Unsupported Generic Pump Function"

I am running the latest testing branch. 

**To Reproduce**
1. Run: sudo OpenCorsairLink.elf --device=0 --pump mode=5

Dev=0, CorsairLink Device Found: H80i GT V2!

Vendor: Corsair
Product: H80i GT V2
Firmware: 2.8.0.0
Temperature 0: 43.20 C
Temperature 1: 43.20 C
Temperature 2: 43.20 C
Fan 0:  Mode 0x30
        Current/Max Speed 0/0 RPM
**Unsupported Generic Pump Function**
Pump:   Mode 0x00
        Current/Max Speed 2700/0 RPM

sudo OpenCorsairLink.elf --dump --device 0
Checking USB device 0 (8087:8002)...
Checking USB device 1 (1d6b:0002)...
Checking USB device 2 (1d6b:0003)...
Checking USB device 3 (1d6b:0002)...
Checking USB device 4 (8087:800a)...
Checking USB device 5 (1d6b:0002)...
Checking USB device 6 (1d6b:0003)...
Checking USB device 7 (1b1c:0c08)...
Corsair product detected. Checking if device is H80i GT V2... Dev=0, CorsairLink Device Found: H80i GT V2!
Checking USB device 8 (051d:0002)...
Checking USB device 9 (1a40:0101)...
Checking USB device 10 (0658:0200)...
Checking USB device 11 (0624:0200)...
Checking USB device 12 (1d6b:0002)...

DEBUG: scan done, start routines
DEBUG: selected device_number = 0
DEBUG: shortcuts set
DEBUG: init done
Vendor: Corsair
Product: H80i GT V2
Firmware: 2.8.0.0
Temperature 0: 45.10 C
Temperature 1: 45.10 C
Temperature 2: 45.10 C
Fan 0:  Mode 0x30
        Current/Max Speed 0/0 RPM
Unsupported Generic Pump Function
Pump:   Mode 0x00
        Current/Max Speed 3030/0 RPM
DEBUG: deinit done

**Expected behavior**
I'd like to be able to change my pump speed via OpenCorsairLink

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.03 LTS
 - Version: Latest testing branch of OpenCorsairLink (12ef1b6)

**Comment by audiohacked** [comment]
This one should be pretty easy to fix. I think there's a disconnect between the logic for the Asetek and the supported functions for the Asetek driver.

**Comment by drammelt** [comment]
Can confirm that fixes this issue

```
Dev=0, CorsairLink Device Found: H80i GT V2!

Vendor: Corsair
Product: H80i GT V2
Firmware: 2.8.0.0
Temperature 0: 33.60 C
Temperature 1: 33.60 C
Temperature 2: 33.60 C
Fan 0:	Mode 0x7C
	Current/Max Speed 0/0 RPM
Pump:	Mode 0x00
	Current/Max Speed 1050/0 RPM
```
