### ISSUE TITLE
H100i GT V2 Can't set the pump mode

### ISSUE THREAD

**Issue by jkvargas** [audiohacked/OpenCorsairLink#226]
➜  OpenCorsairLink git:(master) sudo /usr/local/bin/OpenCorsairLink.elf --device 0 --pump mode=5
Dev=0, CorsairLink Device Found: H100i GT V2!

Vendor: Corsair
Product: H100i GT V2
Firmware: 2.8.0.0
Temperature 0: 32.00 C
Temperature 1: 32.00 C
Temperature 2: 32.00 C
Fan 0:	Mode 0xEB
	Current/Max Speed 0/0 RPM
Unsupported Pump Function
Pump:	Mode 0x05
	Current/Max Speed 2100/0 RPM
Setting pump to mode: 5
Unsupported Pump Function

**Comment by audiohacked** [comment]
Duplicate of #217
