### ISSUE TITLE
How to use libusbx instead of libusb

### ISSUE THREAD

**Issue by Perracomax** [audiohacked/OpenCorsairLink#230]
Hello, as I saw in other issues I should use libusbx instead of libusb in Fedora.
I was looking for something to modify in the files and I see a lot of things pointing to libusb.
My idea is to make a temporal symlink for this, but maybe there is a better way to do that.

Thank you very much and sorry if this is not the better place for this question.

**Comment by audiohacked** [comment]
On Fedora, you shouldn't have to change anything to be using libusbx as the old libusb is just a compatibility layer for libusbx.
