### ISSUE TITLE
How to compile on MacOS?

### ISSUE THREAD

**Issue by ppamorim** [audiohacked/OpenCorsairLink#26]
I am trying to compile this project on my MacOS, but I am getting a lot of errors. Would you help me?
It returns  `'libusb.h' file not found` So you know how to fix it?

EDIT: Creating a C++ project on Xcode solved many problems, but I found some another problem: 
![screen shot 2017-06-11 at 03 31 12](https://user-images.githubusercontent.com/5521682/27007764-ad165054-4e56-11e7-8a40-0c260e587d3f.png)

Seems that method doesn't exist, I did a research on a old code and the code is there, what happened?

EDIT 2: This seems to be a compiler problem, Xcode is not able to build the struct based on parameters/pointers.

**Comment by audiohacked** [comment]
You seem to be on an old version of OpenCorsairLink. please update to the latest release.

**Comment by ppamorim** [comment]
Thank you! I will try it.
