### ISSUE TITLE
Cannot find file: OpenCorsairLink.pro

### ISSUE THREAD

**Issue by marcnotmark** [audiohacked/OpenCorsairLink#28]
Hey all, sorry if this is a complete noob issue.  I'm relatively new, but i followed all the steps to install on the wiki and cloned the repository, but i'm getting an error when i try to do the "qmake OpenCorsairLink.pro" command.  Any help would be appreciated- thanks in advance!

**Comment by Serubin** [comment]
@marcnotmark `OpenCorsairLink.pro` is provided in the [root of the repo](https://github.com/audiohacked/OpenCorsairLink/blob/legacy/OpenCorsairLink.pro).

Make sure it's present there. If it's now, download it, if it is can you run `ls -la .` in the root of the repo and show us the results?

**Comment by marcnotmark** [comment]
Ah I see, let me try that now.  That looks to be on the legacy branch.. should i be pulling everything from there too?

**Comment by audiohacked** [comment]
Please update to the latest release, I will not provide support on the legacy branch.

**Comment by marcnotmark** [comment]
@audiohacked  I had initially downloaded the latest in the master branch but that does not have OpenCorsairLink.pro.

**Comment by Serubin** [comment]
@marcnotmark In the new branch just type in `make` and it will create the elf

**Comment by audiohacked** [comment]
@marcnotmark the master branch doesn't use qmake or OpenCorsairLink.pro. Also, the instructions are for the legacy branch.
