### ISSUE TITLE
H115i Nothing Works

### ISSUE THREAD

**Issue by ChronusDev** [audiohacked/OpenCorsairLink#36]
OpenCorsairLink detects that the H115i is there, but you cannot actually change anything using the software.

**Comment by ioiobzit** [comment]
That's not completely true, you can change the color of the LED.


On 16 July 2017 22:51:09 CEST, ChronusDev <notifications@github.com> wrote:
>OpenCorsairLink detects that the H115i is there, but you cannot
>actually change anything using the software.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/audiohacked/OpenCorsairLink/issues/36

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ChronusDev** [comment]
I personally didn't have any success with changed the LED, however that's most likely a user error here. I only tried 1 color.

**Comment by ChronusDev** [comment]
@ioiobzit thought I'd tell you that the development branch works perfectly for the H115i now.
