### ISSUE TITLE
Source of uint16 to double formula

### ISSUE THREAD

**Issue by mdlayher** [audiohacked/OpenCorsairLink#47]
Hello!  I was spelunking through the source code today when I noticed the function `convert_bytes_double`.

https://github.com/audiohacked/OpenCorsairLink/blob/master/protocol/rmi/core.c#L35

Can you explain how this formula was obtained?  I've ported it to Go and it appears to work fine in my programs as well, though I haven't the faintest idea why.

Thanks for your time.

**Comment by audiohacked** [comment]
It's the standard algorithm to convert two bytes into a double.

**Comment by mdlayher** [comment]
Can you provide any links?  Did a fair amount of Googling last night and couldn't find anything that resembled it.

**Comment by audiohacked** [comment]
https://en.wikipedia.org/wiki/Half-precision_floating-point_format
