### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by jcramer** [audiohacked/OpenCorsairLink#49]
Hi, maybe I'm screwing something up, but getting an error when running make command:

cc -std=c99 -pedantic-errors -I/usr/include/libusb-1.0 -g -c -o options.o options.c
In file included from options.c:26:0:
options.c: In function ‘options_parse’:
common.h:26:23: error: expected ‘)’ before string constant
 #define VERSION MAJOR "." MINOR "." PATCH
                       ^
print.h:37:39: note: in definition of macro ‘msg_info’
 #define msg_info(...) print(MSG_INFO, __VA_ARGS__)
                                       ^~~~~~~~~~~
options.c:82:44: note: in expansion of macro ‘VERSION’
    msg_info("OpenCorsairLink Version: %s", VERSION);
                                            ^~~~~~~
options.c:82:13: warning: format ‘%s’ expects argument of type ‘char *’, but argument 3 has type ‘int’ [-Wformat=]
    msg_info("OpenCorsairLink Version: %s", VERSION);
             ^
print.h:37:39: note: in definition of macro ‘msg_info’
 #define msg_info(...) print(MSG_INFO, __VA_ARGS__)
                                       ^~~~~~~~~~~
Makefile:41: recipe for target 'options.o' failed
make: *** [options.o] Error 1

**Comment by audiohacked** [comment]
Fixed!
