### ISSUE TITLE
Corsair H100i not detected

### ISSUE THREAD

**Issue by bmoscon** [audiohacked/OpenCorsairLink#5]
I have an H100i and its hooked into the USB header on the motherboard:

bryant@bryant-linux:OpenCorsairLink$ lsusb
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 004: ID 1b1c:0c04 Corsair 
...
...

When I run the CLI command, it gives me an error:
bryant@bryant-linux:OpenCorsairLink$ sudo ./OpenCorsairLinkCli -i
Error: Unable to write() (null)
Error: Unable to read() (null)
Device ID:  7 mismatch. Not Corsair H80i or H100i CPU Cooler
Cannot initialize link.

I'm not sure what device ID 7 relates to. Any thoughts?

**Comment by biergaizi** [comment]
I think it's was a strange problem related to firmware? My cooler worked with it for two weeks and now the program ended up with same error message.

**Comment by biergaizi** [comment]
It's must be a certain type of firmware issue. I tried to re-connect the cooler many times, but without success. The system recognized the device without issue after I re-connect it when the computer is powered...

It's a very common problem that some USBs doesn't work until you replugin it after the system starts.
