### ISSUE TITLE
tested ok for RM650i

### ISSUE THREAD

**Issue by jontis** [audiohacked/OpenCorsairLink#53]
I've tested the recent version with RM650i and it seems to work really good.
You can set this as supported too.

All numbers I could verify like temp / voltage / amp / watt are in agreement with official windows software.

sudo ./OpenCorsairLink.elf --dev 0
Dev=0, CorsairLink Device Found: RM650i!

Vendor: CORSAIR
Product: RM650i
Firmware: NA
Temperature 0: 51.00 C
Temperature 1: 41.00 C
Powered: 29923016 (346d.  7h)
Uptime: 39416 (0d.  10h)
Supply Voltage: 230.00
Total Watts: 52.00
Output 12v:
	Voltage 12.22
	Amps  3.00
	Watts 36.00
Output 5v:
	Voltage  5.06
	Amps  2.12
	Watts 11.00
Output 3.3v:
	Voltage  3.34
	Amps  1.12
	Watts  4.00

**Comment by audiohacked** [comment]
Readme updated with RM650i support.
