### ISSUE TITLE
H80i  (HID) looks like pump_index should be 4 i device.c

### ISSUE THREAD

**Issue by n1c0la5** [audiohacked/OpenCorsairLink#60]
Until I changed the .pump_index from 5 to 4 on line 58 I was always getting a Pump Speed of 0, now I get what looks to be a realistic value, around 2100.

--pump-mode 3 or 5 seems to have no effect on this value, so I may be wrong again...

```
Dev=0, CorsairLink Device Found: H80i!
Vendor: Corsair
Product: H80i
Firmware: 0.59.0.0
Temperature 0: 55.38
Temperature 1: 256.00
Fan Speed 0: 2477
Fan Speed 1: 0
Fan Speed 2: 0
Fan Speed 3: 0
Pump Speed: 2118
```
My 2nd fan is broken, waiting for the replacement. Hope that fixes the temp1 and fan2.

**Comment by malakudi** [comment]
N1c0la5, can you check with my pull request about command lengths always at 64 bytes?

--pump-mode does nothing in hid code, a pull request is on the works. At least in my H110i Extreme, pump speed is controlled by setting RPM value (register 0x14)
