### ISSUE TITLE
Fan control not working for h100i v2

### ISSUE THREAD

**Issue by Tahirnaeem** [audiohacked/OpenCorsairLink#66]
hi everyone,

I am trying to control the pump and fan speeds with this tool. I can bring down the pump speeds to something like 1800 but the fan doesnt seem to have any effect. here is snapshot:

![screenshot from 2017-12-06 23-28-02](https://user-images.githubusercontent.com/29177809/33688849-52221a48-dadd-11e7-93ec-b35863832005.png)

Am i using the command wrongly ? In the list only one fan appears and the command "sudo ./OpenCorsairLink.elf --device 0 --fan-speeds 25 --fan-temps 25 --pump-mode 3" has no effect on it. I assumed it will bring down the fan speed to 25 and will set the temprature at which the fan will kick off at 65 but it has no effect. 

My casing has 3 fans at front, 2 at top, 1 at backside. 

Any help much appreciated!

**Comment by audiohacked** [comment]
--fan-speeds and --fan-temps are used to define a fan curve with 6 points
