### ISSUE TITLE
fan speeds unreliable(?)

### ISSUE THREAD

**Issue by JAicewizard** [audiohacked/OpenCorsairLink#69]
how do I set the temperatures?
I use 
`sudo CorsairLink --device 0 --fan-speeds 1500,1500,1500,1500,1500,1500 --fan-temps 20,30,40,50,60,80` (these temps are rediculess, I know. just to make sure that I had the same 6 intergers used in the code)

I tried with all 2500rpm, and a couple of seconds later I couldn't hear my music because of the fans.
then I tried going down with all 1500rpm, which did nothing.like 30 seconds later fans went down to 700 rpm.
but that's not the 1500rpm I was hoping for. Later it went back to 2500 for about 30 seconds, and then down again. 
I use the Corsair H100i V2.

**Comment by djchen** [comment]
I haven't been able to change my H100i V2's fan speeds at all.
This is what I set:

`$ sudo ./OpenCorsairLink.elf --device 0 --fan-temps 20,23,25,28,30 --fan-speeds 1200,1400,1600,1800,2000
Dev=0, CorsairLink Device Found: H100i V2!

Vendor: Corsair
Product: H100i V2
Firmware: 2.8.0.0
Temperature 0: 26.30
Fan Speed 0: 840
Pump Speed: 1980`

When I check on it a few minutes later:
`Temperature 0: 26.30
Fan Speed 0: 900`

**Comment by djchen** [comment]
Seems like this is being worked on in issue #65
