### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by towheed** [audiohacked/OpenCorsairLink#8]
## Just trying to build but fails with:

/usr/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status
Makefile:159: recipe for target '../OpenCorsairLinkGui' failed
make[1]: **\* [../OpenCorsairLinkGui] Error 1
make[1]: Leaving directory '/home/towheed/OpenCorsairLink/Gui'
Makefile:126: recipe for target 'sub-Gui-make_first-ordered' failed
## make: **\* [sub-Gui-make_first-ordered] Error 2

This is the full output from make:
cd CorsairLinkLib/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/towheed/OpenCorsairLink/CorsairLinkLib/CorsairLinkLib.pro -o Makefile ) && make -f Makefile 
make[1]: Entering directory '/home/towheed/OpenCorsairLink/CorsairLinkLib'
g++ -c -m64 -pipe -g -fPIC -Wall -W -D_REENTRANT  -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -o Fan.o Fan.cpp
g++ -c -m64 -pipe -g -fPIC -Wall -W -D_REENTRANT  -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -o Led.o Led.cpp
g++ -c -m64 -pipe -g -fPIC -Wall -W -D_REENTRANT  -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -o Link.o Link.cpp
g++ -c -m64 -pipe -g -fPIC -Wall -W -D_REENTRANT  -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -o Temperature.o Temperature.cpp
rm -f libCorsairLink.a
ar cqs libCorsairLink.a Fan.o Led.o Link.o Temperature.o
rm -f ../libCorsairLink.a
mv -f libCorsairLink.a ../ 
make[1]: Leaving directory '/home/towheed/OpenCorsairLink/CorsairLinkLib'
cd Cli/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/towheed/OpenCorsairLink/Cli/Cli.pro -o Makefile ) && make -f Makefile 
make[1]: Entering directory '/home/towheed/OpenCorsairLink/Cli'
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE -DQT_NO_DEBUG -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I../CorsairLinkLib -o cli.o cli.cpp
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE -DQT_NO_DEBUG -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I../CorsairLinkLib -o options.o options.cpp
g++ -m64 -Wl,-O1 -o ../OpenCorsairLinkCli cli.o options.o   -L.. -lCorsairLink -lhidapi-hidraw -lpthread 
make[1]: Leaving directory '/home/towheed/OpenCorsairLink/Cli'
cd Gui/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/towheed/OpenCorsairLink/Gui/Gui.pro -o Makefile ) && make -f Makefile 
make[1]: Entering directory '/home/towheed/OpenCorsairLink/Gui'
g++ -c -m64 -pipe -g -D_REENTRANT -Wall -W -fPIE -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I../CorsairLinkLib -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -o main.o main.cpp
g++ -c -m64 -pipe -g -D_REENTRANT -Wall -W -fPIE -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I../CorsairLinkLib -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -o window.o window.cpp
g++ -c -m64 -pipe -g -D_REENTRANT -Wall -W -fPIE -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I../CorsairLinkLib -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -o FanWidget.o FanWidget.cpp
g++ -c -m64 -pipe -g -D_REENTRANT -Wall -W -fPIE -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I../CorsairLinkLib -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -o LedWidget.o LedWidget.cpp
g++ -c -m64 -pipe -g -D_REENTRANT -Wall -W -fPIE -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I../CorsairLinkLib -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -o StatusWidget.o StatusWidget.cpp
g++ -c -m64 -pipe -g -D_REENTRANT -Wall -W -fPIE -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I../CorsairLinkLib -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -o TemperatureWidget.o TemperatureWidget.cpp
/usr/lib/x86_64-linux-gnu/qt5/bin/moc -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/towheed/OpenCorsairLink/Gui -I/home/towheed/OpenCorsairLink/CorsairLinkLib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include window.h -o moc_window.cpp
g++ -c -m64 -pipe -g -D_REENTRANT -Wall -W -fPIE -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I../CorsairLinkLib -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -o moc_window.o moc_window.cpp
/usr/lib/x86_64-linux-gnu/qt5/bin/moc -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/towheed/OpenCorsairLink/Gui -I/home/towheed/OpenCorsairLink/CorsairLinkLib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include FanWidget.h -o moc_FanWidget.cpp
g++ -c -m64 -pipe -g -D_REENTRANT -Wall -W -fPIE -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I../CorsairLinkLib -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -o moc_FanWidget.o moc_FanWidget.cpp
/usr/lib/x86_64-linux-gnu/qt5/bin/moc -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/towheed/OpenCorsairLink/Gui -I/home/towheed/OpenCorsairLink/CorsairLinkLib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include LedWidget.h -o moc_LedWidget.cpp
g++ -c -m64 -pipe -g -D_REENTRANT -Wall -W -fPIE -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I../CorsairLinkLib -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -o moc_LedWidget.o moc_LedWidget.cpp
/usr/lib/x86_64-linux-gnu/qt5/bin/moc -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/towheed/OpenCorsairLink/Gui -I/home/towheed/OpenCorsairLink/CorsairLinkLib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include StatusWidget.h -o moc_StatusWidget.cpp
g++ -c -m64 -pipe -g -D_REENTRANT -Wall -W -fPIE -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I../CorsairLinkLib -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -o moc_StatusWidget.o moc_StatusWidget.cpp
/usr/lib/x86_64-linux-gnu/qt5/bin/moc -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/towheed/OpenCorsairLink/Gui -I/home/towheed/OpenCorsairLink/CorsairLinkLib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include TemperatureWidget.h -o moc_TemperatureWidget.cpp
g++ -c -m64 -pipe -g -D_REENTRANT -Wall -W -fPIE -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I../CorsairLinkLib -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -o moc_TemperatureWidget.o moc_TemperatureWidget.cpp
g++ -m64 -o ../OpenCorsairLinkGui main.o window.o FanWidget.o LedWidget.o StatusWidget.o TemperatureWidget.o moc_window.o moc_FanWidget.o moc_LedWidget.o moc_StatusWidget.o moc_TemperatureWidget.o   -L/usr/X11R6/lib64 -L.. -lCorsairLink -lhidapi-hidraw -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
/usr/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status
Makefile:159: recipe for target '../OpenCorsairLinkGui' failed
make[1]: **\* [../OpenCorsairLinkGui] Error 1
make[1]: Leaving directory '/home/towheed/OpenCorsairLink/Gui'
Makefile:126: recipe for target 'sub-Gui-make_first-ordered' failed
make: **\* [sub-Gui-make_first-ordered] Error 2

Any assistance welcomed.

Thanks for supporting this on Linux.  Hope I can get it working.

Towheed

**Comment by audiohacked** [comment]
What Distribution is this on? It looks like its trying to link the OpenGL library, even though there's no dependency on OpenGL.

**Comment by towheed** [comment]
I'm on Debian Testing (Jessie).  I was thinking the same and verified I had the OpenGL libs installed.

It's built to the point where I can run the CLI.  I've only just tested using the -p and -i switches but would also like to get the GUI running.

**Comment by towheed** [comment]
Here's the line in the Gui/Makefile:
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -L.. -lCorsairLink -lhidapi-hidraw -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread

GL?  What lib is that? OpenGL?

**Comment by towheed** [comment]
Removed -lGL from the Makefile and got the it to complete the build but it's very slow to respond to clicks on the menu items.  Any way to set fan speed from the GUI?

**Comment by audiohacked** [comment]
Maybe make sure Qt5 is built with OpenGL!? There's a reason why I don't develop on debian, ubuntu, or fedora...

**Comment by towheed** [comment]
I think it is....but the Qt5 OpenGL dev libs are also installed.

This is a new build, I'll see if it has anything to with the nVidia drivers as I installed directly and not from the Debian packages.

The CLI works wonderful, thanks for that.
Is there some way to interface this with say Conky, just as an example, or even lm-sensors.
