### ISSUE TITLE
Unlisted Dependency: pkg-config

### ISSUE THREAD

**Issue by jrdoane** [audiohacked/OpenCorsairLink#82]
In addition to libusb-1.0, you also need pkg-config to build the project in Ubuntu 17.10, otherwise building the project will fail and provide an error stating that libusb.h could not be found.

**Comment by audiohacked** [comment]
pkg-config honestly is pretty standard software for Linux/UNIX. As to why Ubuntu doesn't have it install by default; I don't know. I've updated the README to reflect the problem
