### ISSUE TITLE
How to output current status of the cooler

### ISSUE THREAD

**Issue by njuaplusplus** [audiohacked/OpenCorsairLink#83]
Thanks for this project!
But I can't find how to output the current status of the cooler.

When I type in:
```
sudo ./OpenCorsairLink.elf –-device 0
```
It just output:
```
Dev=0, CorsairLink Device Found: H100i GTX!
```
But there is no additional information.
Did I miss anything?

**Comment by audiohacked** [comment]
Something more should have printed.

**Comment by njuaplusplus** [comment]
@audiohacked Hi. Thanks for your reply. I wonder what should I do to figure it out?

**Comment by njuaplusplus** [comment]
@audiohacked I wonder why you closed this issue.

**Comment by audiohacked** [comment]
There's nothing I can do to get it to work. You can try to update the firmware via Windows.

**Comment by njuaplusplus** [comment]
Got it. Thank you.
