### ISSUE TITLE
Problem when executing more than once (H115i)

### ISSUE THREAD

**Issue by ghost** [audiohacked/OpenCorsairLink#92]
If i use ./OpenCorsairLink.elf --device=0 more than once, the fans start spinning at max speed and if I do it one more time after they spin up to max, they almost shut of or go to minimal speed.
This means that even if I try to set a fan mode or a pump mode, I can't check how it's doing without the risk of it resetting again.

**Comment by audiohacked** [comment]
I recently pushed a change that should only read the device info without changing anything.
