### ISSUE TITLE
H150i Pro

### ISSUE THREAD

**Issue by RobP76** [audiohacked/OpenCorsairLink#95]
Hello could you tell me if the Corsair H150i Pro work please? 

Thanks

Rob

**Comment by RobP76** [comment]
Does it work on the same driver?

Sent from Mail for Windows 10

**Comment by audiohacked** [comment]
Yes, the driver is the same for both H150i Pro and H115i Pro.

**Comment by RobP76** [comment]
Ive only just got the cooler and I had to install windows to use it properly ill try Linux with your opencorsairlink and hope for the best

Sent from Mail for Windows 10
