### ISSUE TITLE
LL120 fans

### ISSUE THREAD

**Issue by tgeorgiop** [audiohacked/OpenCorsairLink#96]
Hello. Does this work with ll120 fans? Thanks.

**Comment by audiohacked** [comment]
I don't know. Does it?

**Comment by Belval** [comment]
What is your LL120 setup @tgeorgiop ? Are you using a commander pro, a lightning node pro, etc..?

Also what do you mean by "work" what do you want to achieve?

**Comment by audiohacked** [comment]
I'm closing this since we haven't gotten any response in almost 2 weeks.

**Comment by vlinkz** [comment]
Will it be possible to control (change led settings/fan speed) the LL120 fans with the Commander Pro any time soon? Currently, I can't make the Commander Pro do anything with OpenCorsairLink. Thanks.

**Comment by Vagr9K** [comment]
Hey everyone!

I'm using LL120 with Lightning Node Pro, and apparently those fans don't have "hardware profiles" and get stuck on rainbow mode while on Linux.

I'd like to help you guys, but I'm not sure how.

**Comment by vlinkz** [comment]
@Vagr9K, I believe that if you have the Lighting Node Pro you can use [Colorsair](https://github.com/Chlorek/Colorsair) to change the fan color/animations

**Comment by Vagr9K** [comment]
Thanks @vlinkz!

**Comment by shaneshort** [comment]
Hi Guys,
The LL Fans are no different than standard addressable lighting strips, it shouldn't be too difficult to figure the logic out.

**Comment by benburkhart1** [comment]
Hey all, figured out this protocol for Lighting Node Pro + Corsair LL fans, I have the reversing information and a demo project available here:

https://github.com/benburkhart1/lighting-node-pro
