### ISSUE TITLE
Cant change any setting...

### ISSUE THREAD

**Issue by soofstad** [audiohacked/OpenCorsairLink#98]
So it's kinda hard to find any concrete answer to how this works. So many issues are closed before any proper explanation is given.

So, can you really only set any configuration once?!

I understand that a profile is written to the onboard storage of the pump (in my case H100i).
If there is no way to write again with OpenCorsaidLink, does anyone know how to "factory reset" the onboard storage so I'm able to run OpenCorsairLink a second time?

**Comment by audiohacked** [comment]
Nothing is written to "onboard" storage. If you shut off the computer all your settings are lost! Please take the time to read the command help!

**Comment by audiohacked** [comment]
It's not my problem if you can't take the time to figure out how the software works!
